version: '3'

services:
  todolist:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: todolist
    working_dir: /code
    volumes:
      - ./:/code:delegated,rw
    networks:
      - rede1

  nginx:
    image: nginx:latest
    depends_on:
      - "todolist"
    links:
      - todolist
    ports:
      - "9090:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/code
    networks:
      - rede1

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - rede1

volumes:
  database_data:

networks:
  rede1:
    driver: bridge